language: ruby
sudo: required
services:
  - docker

script:
  - docker build -t telusdigital/telusdigital-hubot:v_TRAVIS_BUILD_NUMBER .

deploy:
  - provider: elasticbeanstalk
    app: telusdigital-hubot
    env: telusdigital-hubot-prod
    bucket_name: elasticbeanstalk-us-east-1-461957644563
    region: us-east-1
    access_key_id:
      secure: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: $AWS_SECRET_ACCESS_KEY
    on:
      repo: telusdigital/telusdigital-hubot
      branch: master
      condition: "$TRAVIS_BRANCH = master"
