language: ruby
sudo: required
services:
  - docker

script:
  - docker build -t telusdigital/wasimbot .
  - docker run -d telusdigital/wasimbot

deploy:
  - provider: elasticbeanstalk
    app: wasimbot
    env: wasimbot-prod
    bucket_name: elasticbeanstalk-us-east-1-461957644563
    region: us-east-1
    access_key_id:
      secure: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: $AWS_SECRET_ACCESS_KEY
    on:
      repo: telusdigital/wasimbot
      branch: master
      condition: "$TRAVIS_BRANCH = master"
